# Use root/example as user/password credentials

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    network_mode: host
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: normaluser
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# networks:
#   host:  # Network must be defined here
#     driver: host